name: Branch Push CI

on:
  schedule:
    - cron: '30 15,9 * * *'
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for scripts/upload-apk.sh
      run: chmod +x scripts/upload-apk.sh
    - name: Deploy to Branch
      run: ./scripts/upload-apk.sh
      env:
        PAT: ${{ secrets.PAT }}
