name: Branch Push CI

on:
  schedule:
    - cron: '30 15,9 * * *'
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'
    - run: flutter pub get
    - run: flutter build apk --no-sound-null-safety
    - run: flutter build appbundle --no-sound-null-safety